# Python Project - Data Cleaning for Movies Dataset
## by Asare Samuel

## Introduction
>  ### The movies dataset is a popular dataset on the internet. It contains fields such as movies,year,genre, rating,year it was produced and movie gross earnings.This project is to clean the data, getting it ready for Visualization. 
### First import our pandas library, to help us read in our csv file.

In [2]:
pd.read_csv('movies.csv')

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
9994,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n \n Stars:\nMorgan Taylor Camp...,NaN,NaN,NaN
9995,Arcane,(2021– ),"\nAnimation, Action, Adventure",NaN,\nAdd a Plot\n,\n,NaN,NaN,NaN
9996,Heart of Invictus,(2022– ),"\nDocumentary, Sport",NaN,\nAdd a Plot\n,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,NaN,NaN
9997,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN
9998,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN

>  ### After our CSV file is read in, we assign it to an alias(df) to make future readings easier.

In [3]:
df=pd.read_csv('movies.csv')

In [4]:
df

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
9994,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n \n Stars:\nMorgan Taylor Camp...,NaN,NaN,NaN
9995,Arcane,(2021– ),"\nAnimation, Action, Adventure",NaN,\nAdd a Plot\n,\n,NaN,NaN,NaN
9996,Heart of Invictus,(2022– ),"\nDocumentary, Sport",NaN,\nAdd a Plot\n,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,NaN,NaN
9997,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN
9998,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n Director:\nJovanka Vuckovic\n| \n Sta...,NaN,NaN,NaN

### CLEANING

> ### The first cleaning operation is to get rid of all duplicate rows in our table. We have to write code to actually figure out if we have duplicate rows.

In [5]:
df.MOVIES.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9994     True
9995    False
9996    False
9997     True
9998     True
Name: MOVIES, Length: 9999, dtype: bool

In [6]:
sum(df.MOVIES.duplicated())

3182

In [7]:
df.drop_duplicates('MOVIES',inplace=True)

In [8]:
df

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
9935,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n \n Stars:\nMorgan Taylor Camp...,NaN,NaN,NaN
9964,AlRawabi School for Girls,(2021),\nDrama,NaN,\nAdd a Plot\n,\n Director:\nTima Shomali\n| \n Stars:\...,NaN,NaN,NaN
9993,Totenfrau,(2022– ),"\nDrama, Thriller",NaN,\nAdd a Plot\n,\n Director:\nNicolai Rohde\n| \n Stars:...,NaN,NaN,NaN
9995,Arcane,(2021– ),"\nAnimation, Action, Adventure",NaN,\nAdd a Plot\n,\n,NaN,NaN,NaN
9996,Heart of Invictus,(2022– ),"\nDocumentary, Sport",NaN,\nAdd a Plot\n,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,NaN,NaN

> ### Reset the index to have columns in the right order.

In [9]:
df.reset_index(inplace=True,drop=True)

In [10]:
df

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
6812,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n \n Stars:\nMorgan Taylor Camp...,NaN,NaN,NaN
6813,AlRawabi School for Girls,(2021),\nDrama,NaN,\nAdd a Plot\n,\n Director:\nTima Shomali\n| \n Stars:\...,NaN,NaN,NaN
6814,Totenfrau,(2022– ),"\nDrama, Thriller",NaN,\nAdd a Plot\n,\n Director:\nNicolai Rohde\n| \n Stars:...,NaN,NaN,NaN
6815,Arcane,(2021– ),"\nAnimation, Action, Adventure",NaN,\nAdd a Plot\n,\n,NaN,NaN,NaN
6816,Heart of Invictus,(2022– ),"\nDocumentary, Sport",NaN,\nAdd a Plot\n,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,NaN,NaN

> ### Make all column names lowercase to make them easy to work with

In [14]:
df.columns=df.columns.str.lower()

In [15]:
df

,movies,year,genre,rating,one-line,stars,votes,runtime,gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
6812,The Imperfects,(2021– ),"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n \n Stars:\nMorgan Taylor Camp...,NaN,NaN,NaN
6813,AlRawabi School for Girls,(2021),\nDrama,NaN,\nAdd a Plot\n,\n Director:\nTima Shomali\n| \n Stars:\...,NaN,NaN,NaN
6814,Totenfrau,(2022– ),"\nDrama, Thriller",NaN,\nAdd a Plot\n,\n Director:\nNicolai Rohde\n| \n Stars:...,NaN,NaN,NaN
6815,Arcane,(2021– ),"\nAnimation, Action, Adventure",NaN,\nAdd a Plot\n,\n,NaN,NaN,NaN
6816,Heart of Invictus,(2022– ),"\nDocumentary, Sport",NaN,\nAdd a Plot\n,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,NaN,NaN

> ### Extract only the year from the year column

In [17]:
df.year.str.extract('(\d{4})')

         0
0     2021
1     2021
2     2010
3     2013
4     2021
...    ...
6812  2021
6813  2021
6814  2022
6815  2021
6816  2022

[6817 rows x 1 columns]

In [18]:
df.year=df.year.str.extract('(\d{4})')

In [19]:
df

,movies,year,genre,rating,one-line,stars,votes,runtime,gross
0,Blood Red Sky,2021,"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,2021,"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,2010,"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,2013,"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,2021,"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
6812,The Imperfects,2021,"\nAdventure, Drama, Fantasy",NaN,\nAdd a Plot\n,\n \n Stars:\nMorgan Taylor Camp...,NaN,NaN,NaN
6813,AlRawabi School for Girls,2021,\nDrama,NaN,\nAdd a Plot\n,\n Director:\nTima Shomali\n| \n Stars:\...,NaN,NaN,NaN
6814,Totenfrau,2022,"\nDrama, Thriller",NaN,\nAdd a Plot\n,\n Director:\nNicolai Rohde\n| \n Stars:...,NaN,NaN,NaN
6815,Arcane,2021,"\nAnimation, Action, Adventure",NaN,\nAdd a Plot\n,\n,NaN,NaN,NaN
6816,Heart of Invictus,2022,"\nDocumentary, Sport",NaN,\nAdd a Plot\n,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,NaN,NaN

> ### Extract the first genre from the genre column. First split the column using the commma delimiter.

In [20]:
df.genre.str.split(',',expand=True)

                        0                      1                       2
0                \nAction                 Horror    Thriller
1             \nAnimation                 Action   Adventure
2                 \nDrama                 Horror    Thriller
3             \nAnimation              Adventure      Comedy
4                \nAction                  Crime      Horror
...                   ...                    ...                     ...
6812          \nAdventure                  Drama     Fantasy
6813  \nDrama                               None                    None
6814              \nDrama   Thriller                                None
6815          \nAnimation                 Action   Adventure
6816        \nDocumentary      Sport                                None

[6817 rows x 3 columns]

> ### Select the first cloumn using indexing

In [22]:
df.genre.str.split(',',expand=True)[0]

0                  \nAction
1               \nAnimation
2                   \nDrama
3               \nAnimation
4                  \nAction
               ...
6812            \nAdventure
6813    \nDrama
6814                \nDrama
6815            \nAnimation
6816          \nDocumentary
Name: 0, Length: 6817, dtype: object

> ### Get rid of unwanted characters infront of the genres

In [23]:
df.genre=df.genre.str.split(',',expand=True)[0].str[1:]

In [24]:
df

,movies,year,genre,rating,one-line,stars,votes,runtime,gross
0,Blood Red Sky,2021,Action,6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,2021,Animation,5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,2010,Drama,8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,2013,Animation,9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,2021,Action,NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
6812,The Imperfects,2021,Adventure,NaN,\nAdd a Plot\n,\n \n Stars:\nMorgan Taylor Camp...,NaN,NaN,NaN
6813,AlRawabi School for Girls,2021,Drama,NaN,\nAdd a Plot\n,\n Director:\nTima Shomali\n| \n Stars:\...,NaN,NaN,NaN
6814,Totenfrau,2022,Drama,NaN,\nAdd a Plot\n,\n Director:\nNicolai Rohde\n| \n Stars:...,NaN,NaN,NaN
6815,Arcane,2021,Animation,NaN,\nAdd a Plot\n,\n,NaN,NaN,NaN
6816,Heart of Invictus,2022,Documentary,NaN,\nAdd a Plot\n,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,NaN,NaN

In [25]:
df.head(3)

,movies,year,genre,rating,one-line,stars,votes,runtime,gross
0,Blood Red Sky,2021,Action,6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,2021,Animation,5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,2010,Drama,8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN

In [26]:
df.drop('one-line',axis=1,inplace=True)

In [27]:
df

,movies,year,genre,rating,stars,votes,runtime,gross
0,Blood Red Sky,2021,Action,6.1,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,2021,Animation,5.0,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,2010,Drama,8.2,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,2013,Animation,9.2,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,2021,Action,NaN,\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
6812,The Imperfects,2021,Adventure,NaN,\n \n Stars:\nMorgan Taylor Camp...,NaN,NaN,NaN
6813,AlRawabi School for Girls,2021,Drama,NaN,\n Director:\nTima Shomali\n| \n Stars:\...,NaN,NaN,NaN
6814,Totenfrau,2022,Drama,NaN,\n Director:\nNicolai Rohde\n| \n Stars:...,NaN,NaN,NaN
6815,Arcane,2021,Animation,NaN,\n,NaN,NaN,NaN
6816,Heart of Invictus,2022,Documentary,NaN,\n Director:\nOrlando von Einsiedel\n| \n ...,NaN,NaN,NaN

> ### Only show the stars of the movie and nothing else from the stars column.

In [32]:
df.stars=df.stars.str.split('Stars',expand=True)[1].str.replace('\n','').str.replace(':','')

In [33]:
df

,movies,year,genre,rating,stars,votes,runtime,gross
0,Blood Red Sky,2021,Action,6.1,"Peri Baumeister, Carl Anton Koch, Alexander Sc...","21,062",121.0,NaN
1,Masters of the Universe: Revelation,2021,Animation,5.0,"Chris Wood, Sarah Michelle Gellar, Lena Headey...","17,870",25.0,NaN
2,The Walking Dead,2010,Drama,8.2,"Andrew Lincoln, Norman Reedus, Melissa McBride...","885,805",44.0,NaN
3,Rick and Morty,2013,Animation,9.2,"Justin Roiland, Chris Parnell, Spencer Grammer...","414,849",23.0,NaN
4,Army of Thieves,2021,Action,NaN,"Matthias Schweighöfer, Nathalie Emmanuel, Ruby...",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
6812,The Imperfects,2021,Adventure,NaN,"Morgan Taylor Campbell, Chris Cope, Iñaki Godo...",NaN,NaN,NaN
6813,AlRawabi School for Girls,2021,Drama,NaN,"Salsabiela A., Joanna Arida, Yara Mustafa, Rak...",NaN,NaN,NaN
6814,Totenfrau,2022,Drama,NaN,"Felix Klare, Romina Küper, Anna Maria Mühe, Ro...",NaN,NaN,NaN
6815,Arcane,2021,Animation,NaN,None,NaN,NaN,NaN
6816,Heart of Invictus,2022,Documentary,NaN,None,NaN,NaN,NaN

> ### Save the file to csv

In [34]:
df.to_csv('my_cleaned_movies_dataset.csv',index=False)